'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const load=async name=>{const r=await fetch(`data/${name}`);if(!r.ok)throw new Error(`无法载入 ${name}`);return r.json()};
const text=(tag,value,cls)=>{const e=document.createElement(tag);if(cls)e.className=cls;e.textContent=value??'—';return e};
const link=(label,href)=>{const a=text('a',label);a.href=href;return a};
const norm=v=>(v??'').trim().replace(/\s+/g,' ').toLocaleLowerCase('zh-CN');
function nav(){const b=$('.nav-toggle'),n=$('nav');b?.addEventListener('click',()=>{n.classList.toggle('open');b.setAttribute('aria-expanded',String(n.classList.contains('open')))})}
function recordHref(id){return `record.html?id=${encodeURIComponent(id)}`}
function badge(level){const b=text('span',`${level}级`,`badge lv-${level}`);return b}
function card(r){const a=document.createElement('a');a.className='card';a.href=recordHref(r.record_id);a.append(badge(r.verification_level),text('strong',r.standard_title),text('span',`${r.record_id} · ${r.region} · ${r.era||'时代待考'}`));return a}
async function home(){const [rs,ts]=await Promise.all([load('records.json'),load('themes.json')]);rs.slice(0,6).forEach(r=>$('#featured').append(card(r)));ts.filter(t=>t.level==='一级').forEach(t=>$('#theme-entries').append(link(t.theme_name,`themes.html?theme=${encodeURIComponent(t.theme_id)}`)))}
function searchSubmit(){const f=$('#global-search');f?.addEventListener('submit',e=>{e.preventDefault();location.href=`records.html?q=${encodeURIComponent($('#global-q').value.trim())}`})}
document.addEventListener('DOMContentLoaded',async()=>{nav();searchSubmit();try{const page=document.body.dataset.page;if(page==='home')await home();if(page==='records')await window.initRecords();if(page==='record')await window.initRecord();if(['persons','families','places','themes','sources','leads'].includes(page))await initDirectory(page)}catch(e){console.error(e);const m=$('main');m.append(text('p','数据载入失败，请确认网站由 HTTP 服务器访问。','notice'))}});
async function initDirectory(kind){const data=await load(`${kind}.json`),root=$('#directory');if(kind==='leads'){data.forEach(x=>{const a=document.createElement('article');a.className='card';a.append(badge('D'),text('h2',x.lead_title),text('p',`当前问题：${x.current_issue||'—'}`),text('p',`建议动作：${x.recommended_action||'—'}`),text('small',`跟进状态：${x.follow_up_status||'—'}`));root.append(a)});return}const q=new URLSearchParams(location.search).get('theme');let shown=data;if(q&&kind==='themes')shown=data.filter(x=>x.theme_id===q||x.parent_theme_id===q);shown.forEach(x=>{const a=document.createElement('article');a.className='card';const name=x.standard_name||x.historical_name||x.modern_name||x.theme_name||x.source_title;a.append(text('h2',name),text('p',x.definition||x.note||x.era||x.primary_place||x.author_or_institution||'暂无补充说明'));const list=document.createElement('div');list.className='tags';(x.records||[]).forEach(r=>list.append(link(`${r.standard_title}${r.relation_type?' · '+r.relation_type:''}`,recordHref(r.record_id))));a.append(list);root.append(a)})}
